name: ci/cd lr

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Run testing
      - name: Testing..
        run: mvn test


  build:
    # Build an environment
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

        # Message
      - name: Nothing... just a message
        run: echo "can I order an uuuuummm..."

      # Make a package based on our pom.xml
      - name: Build with Maven
        run: mvn -B package --file pom.xml
